### ISSUE TITLE
Update Albany repo path for nightlies!

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#416]
Per issue #415, the Albany repo has moved.  All the nightly tests need to be updated to point to the new repo, which is located here:
```
git@github.com:SNLComputation/Albany.git
```
The following builds need this change:

albany_Fedora_proxima.ca.sandia.gov_serial-gcc-release 
albany_SEMS_ceerws1006_serial-gcc-release 
albany_Fedora_algol.ca.sandia.gov_serial-clang-release 
albany_SEMS_ceerws1006_serial-intel-release 
albany_cluster-toss3_skybridge-login5_serial-intel-release 

I believe these are all owned by @lxmota .  Alejandro, can you please make the change when you return?

**Comment by bartgol** [comment]
When I checked the nightlies today, I saw references to the old repo (which, when clicked, give a 404 not found error).

See, e.g., [here](http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=85637)

**Comment by lxmota** [comment]
@bartgol @ikalash Weird. I checked and *all* the builds in CDash make reference to the old repo when they issue warnings of error. First I checked all LCM directories, but I could not find any reference to the old repo anywhere. This is probably coming from the configuration in the CDash site, since all builds have it, not just mine.

**Comment by bartgol** [comment]
I greeped and the only occurrences of `ghansen` are in the doc folder. @ikalash could it be that the chronjobs still need to be updated somehow?

**Comment by ikalash** [comment]
Which nightlies use the old path?  None of the ones I own should..l

**Comment by lxmota** [comment]
@ikalash @bartgol All of them make reference to the old repo: yours, mine. See here, for instance:

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?type=1&buildid=85734
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?type=1&buildid=85761
http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?type=1&buildid=85749

and so on.

**Comment by ikalash** [comment]
I can’t access these links while on foreign travel.  Can you please tell me which machines are problematic?  I think if we were pointing to the old repo there would be other symptoms (the recent pr merge would not be affecting the nightlies).  I’m pretty confident i updated everything while back but I’ll double check when I return.

**Comment by ikalash** [comment]
I strongly suspect the path is coming from cdash (just read the comments above), not that the code is obtained from the old repo.  I’ll check Monday when I return to the office.

**Comment by lxmota** [comment]
@ikalash I think there isn't a problem in that all builds are checking out from the correct Albany repo. It's just that *all* builds give a link to the old repo when they issue warnings and errors. I think this is coming from the CDash site.

**Comment by ikalash** [comment]
I see.  I’ll fix it when I return.  I’m an admin for the cdash sites.

**Comment by ikalash** [comment]
I just made a change by logging in to the Albany CDash sites that should fix this issue.  Lets double check the nightlies tomorrow, then close this issue.  Sorry again about the delay.

**Comment by ikalash** [comment]
It seems I can't verify for sure since there are no build failures at the moment, but this issue should have been resolved by my changes yesterday; therefore closing.

**Comment by ikalash** [comment]
My changes to the CDash site did not fix this issue somehow.  @gahansen do you know why the path reported in case of a failed build by CDash still points to the old repo?  See here for example: 

http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=86172 

in particular the line: https://github.com/gahansen/Albany/blob/5943daa8723d765c75f41ccdfb506113f20fbecb/repos/Albany/src/disc/stk/Albany_GenericSTKMeshStruct.cpp .  I logged onto CDash as an administrator and replaced all paths in the Albany project with the new path.  Where is it getting the old path from?

**Comment by bartgol** [comment]
@ikalash Naive question: do any of the scripts in the doc folder get used for the nightly tests? Some of them still contain "gahansen". I _think_ they are just legacy scripts that are no longer used, but just in case...

**Comment by ikalash** [comment]
The relevant files would be in Albany/doc/dashboards.  If you grep the directory for "gahansen", only penn.srn.sandia.gov comes up, which is Andy's old machine and not relevant.  So I think the path is coming from somewhere in the CDash site.  I just can't seem to figure out where, since I changed it everywhere I found it.  Perhaps @gahansen will know.

**Comment by bartgol** [comment]
@ikalash, on the main page of the cdash project, I clicked on `Project->Repository` and it sent me to @gahansen 's one, which says it's a fork from @SNLComputation/albany . Interestingly, clicking on `Project->Home` sends me to the correct repo. So you're right, it's definitely something with the cdash setup. I don't think I can enter the settings of the cdash, but perhaps cdash allows to specify both home and repo urls, and in our case the repo one is still wrong?

**Comment by ikalash** [comment]
Ah, I think I found the culprit.  I think it should be fixed now, but lets keep this open until there is another failed build, so we can double check.

**Comment by bartgol** [comment]
So, the references to @gahansen are gone, but the links are still wrong. I think cdash is forming the link by cat-ing the repo address (which is the one on github) with the suffix `blob/master/repos/Albany`, followed by the path to the source file. See. e.g., at the top of [this](http://cdash.sandia.gov/CDash-2-3-0/viewBuildError.php?buildid=86258) page.

I don't know where the 'blob/master/blahblah' part comes from. I peeked into other projcets from cdash, and they all have that structure of the address: github repo + blob/tag + path/to/file. So I guess this has to do with cdash way of reporting errors, but I'm not sure if it's a problem on cdash's side or on the user side, who are failing to specify correctly something.

**Comment by ikalash** [comment]
@bartgol : I see.  The "blob" part gets appended automatically by CDash if you select that your repo is a github repo.  You can see it in the attached screenshot.  In particular, it will try to create the following link: 

https://github.com/SNLComputation/blob/REVISION/DIRECTORYNAME/FILENAME

I think we need "blob" to be replaced by "tree".  This seems to be a CDash issue/bug, as I can't figure out how to accomplish it using the admin user interface.  @gahansen perhaps you know?  Here is some documentation online: https://public.kitware.com/Wiki/CDash:Administration#Creating_a_project .

![CDash_screen_shot](https://user-images.githubusercontent.com/7018124/60390080-8ee4c600-9a8b-11e9-8eeb-0006e24dd1d7.png)
