### ISSUE TITLE
Failing FO_GIS_GisAdjointSensitivityBasalFriction tests in CEE clang build 

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#433]
This is a spin-off from issue #413, which uncovered that the following tests fail in the Clang build on the CEE: 

```
FO_GIS_GisAdjointSensitivityBasalFriction
FO_GIS_GisAdjointSensitivityBasalFrictionTpetra
```

http://cdash.sandia.gov/CDash-2-3-0/viewTest.php?onlyfailed&buildid=81426 

Please see the discussion in #413 for more information.

**Comment by bartgol** [comment]
I just pushed a commit that may fix this.

**Comment by ikalash** [comment]
Your commit @bartgol didn't fix the problem, but mine just now should have.  We need to be careful about using auto, apparently.

**Comment by bartgol** [comment]
Ah, that makes sense. Comparing a Sacado Expression with a number is probably wrong (though I'm surprised it even compiles). Another safe workaround there could have been to compare agains `MeshScalarT(0.0)`. But your fix should do. Thanks!

**Comment by ikalash** [comment]
I might have been the one to put that in when I was trying to fix the FPEs coming from Sacado not playing nicely with std::pow...  if that was the case, I am sorry!

**Comment by bartgol** [comment]
No worries. I like `auto` too.
