### ISSUE TITLE
Failing LandIce tests in nightlies due to NullSpace utils refactor

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#609]
The PR that went in yesterday on the Albany NullSpace utils refactor is causing 3 land ice tests to fail in some of the nightlies:

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3637 

The tests are FO_GIS_AdjointSensitivity_StiffeningBasalFriction__Epetra, FO_Test_ConfinedShelf_DepthIntBC_Epetra and FO_Test_ConfinedShelf_Epetra.  Note that they are all Epetra tests.  One unique feature of the machine where the tests fail is it uses the newest gcc we have in the nightlies (10.1.1).  I was able to get a backtrace of the error using gdb - please see attached .txt file.  @mperego, can you please have a look at this?  
[gdb_out.txt](https://github.com/SNLComputation/Albany/files/4887354/gdb_out.txt)

**Comment by mperego** [comment]
@ikalash I pushed a possible fix. It's a wild guess..

**Comment by ikalash** [comment]
I will test it...  stay tuned.

**Comment by ikalash** [comment]
Unfortunately it doesn't fix the issue.  In an effort to debug this, I put print statements in ML to figure out where the code dies.  It dies in ml_aggregate.c, around the "IKT here 4.11" and "IKT here 4.12" print statements in the attached file.  Maybe we should ask for Ray to weigh in?  @rstumin, Mauro recently refactored the way the RBMs are created in Albany which led to failures for some of the Epetra-based ALI tests in ml_aggregate.c - do you have any insight into what might be causing the behavior we're seeing, described here?  I am attaching the output from the run with my print statements as well as the null.0.txt file that was written by activating ML_AGGR_NSOUTPUT in this file.  There are a bunch of messed up values in there suggesting un-initialized quantities.
[out.txt](https://github.com/SNLComputation/Albany/files/4887692/out.txt)
[null.0.txt](https://github.com/SNLComputation/Albany/files/4887693/null.0.txt)
[ml_aggregate.c.txt](https://github.com/SNLComputation/Albany/files/4887691/ml_aggregate.c.txt)

**Comment by mperego** [comment]
I tried printing out null.0.txt, as you did. But they look perfectly fine with my compiler.  It could be that the null space data are overwritten in your case. Trying a couple more things.

**Comment by rstumin** [comment]
I looked at the code, output, and null file.  It is not totally clear what is going on  ... but it does look like the null space is corrupted. I remember we had some issues with the null space in the past but these were connected to its reuse (over multiple solves) ... and this seems to happen on the very first solve ... so I don't think that is the problem either.


It really looks like the nullspace is just coming in messed up? You could perhaps just put a couple of prints right at the top of this ML_Aggregate_Set_NullSpace() function to see what the pointer is ... and what the first few values of null_vect are?


printf("IKT NullSpacePtr inside ML_Aggregate_Set_NullSpace = %u\n',null_vect);

printf("IKT 1st two components %e %e\n',null_vect[0],null_vect[1]);



As I believe you have already figured out, this function is generally called from SetNullSpace() in the file ml_MultiLevelPreconditioner_NullSpace.cpp ... so you could also print the first couple of nullspace values there as well. You should be in the 'pre-computed' section of the code ... which basically does


    NullSpacePtr = List_.get("null space: vectors", NullSpacePtr);


I'd put a print right after this to see what the first couple of values are ? If this is messed up, then I sort of feel that the problem is upstream of ML.

-Ray

?





________________________________

**Comment by ikalash** [comment]
@rstumin : thanks for the reply.  Mauro pushed a patch last night that fixed the issue on my workstation camobap.  It looks like the confined shelf test, Epetra version, is now failing in a couple other nightlies: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=3689 .  @mperego I'm not sure if this is related to your patch.  The fails weren't there yesterday.

**Comment by mperego** [comment]
I think I found the real issue..  I was passing a vector by value instead of by reference!

**Comment by ikalash** [comment]
This has been resolved, it looks like.  Thanks @mperego!
