### ISSUE TITLE
LandIce test failures on weaver

### ISSUE THREAD

**Issue by ikalash** [SNLComputation/Albany#627]
I've gotten the weaver nightlies posting to the CDash site, finally.  It looks like there are a handful of LandIce failures:

```
Enthalpy_Humboldt
FO_GIS_AdjointSensitivity_BasalFriction_Tpetra 
FO_GIS_AdjointSensitivity_StiffeningBasalFriction_Tpetra
FO_GIS_AdjointSensitivity_Tpetra
FO_GIS_ForwardSensitivity_Tpetra
FO_GIS_SensSMBwrtBeta_Tpetra
FO_MMS_FO_SMB_QUAD
```
https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=5112

@jewatkins , @mcarlson801 , @bartgol : can you please have a look?  This could be related to #625 .

**Comment by jewatkins** [comment]
I'm seeing the same thing on ride. I think this is related to 99e4c630ad0f7dfb7595b0f0eb33e22694f605fb but I'm not sure what's causing it. We'll have to investigate this further.

**Comment by mcarlson801** [comment]
I pushed some changes to fix the performance timeouts on Weaver but it looks like it exacerbated the test failures. I'm going to do some digging, I assume there is a bug in the boundary condition PR causing memory corruption.

**Comment by ikalash** [comment]
Are you referring to the new failures that started today (the "18" in the dashboard for a bunch of builds: https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany&date=2020-08-18&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly )?

**Comment by mcarlson801** [comment]
Yes, the new failures today were due to the fix I pushed yesterday for the Weaver issues. I've reverted the fix and now the tests are passing. Now I'm digging into why yesterday's fix caused these problems and I'm hoping it sheds some light on the Ride test failure.

**Comment by jewatkins** [comment]
Weaver issues - referring to the stokesfo finite element assembly performance tests that have been failing on weaver. That is still an issue but this one should be fixed now with the revert (just checked and tests are clean). Let's make a new issue for the performance tests and close this tomorrow when the nightlies come back clean.

**Comment by ikalash** [comment]
@mcarlson801 : ok, great, thank you for looking at it!

**Comment by jewatkins** [comment]
This looks fixed.
