### ISSUE TITLE
Issue with Ascii2D Discretization Method after changes to Block Discretization 

### ISSUE THREAD

**Issue by mperego** [SNLComputation/Albany#636]
As @ikalash pointed out at the Albany meeting there has been a problem w/ Ascii2D method after the merge of PR #632 that was showing up in one of the CALI tests.
To make it easier to debug, and improve test coverage, I added test `FO_GIS_Import2DAsciiMesh_Serial` which is now failing in the nightlies

https://sems-cdash-son.sandia.gov/cdash//queryTests.php?project=Albany&date=2020-10-11&filtercount=2&showfilters=1&filtercombine=and&field1=groupname&compare1=61&value1=Nightly&field2=status&compare2=62&value2=passed

@gahansen do you mind having a quick look at that and see if you understand what's the probelm? I checked and it was working before PR #632.

**Comment by gahansen** [comment]
Sounds great Mauro. I'll take a look and report back soon.

**Comment by gahansen** [comment]
Hi Mauro. I just pushed a fix for this that should take care of it. I wrote the details in the commit message, but the new stk declare_part_with_topology() call that I used required a different description for a 2D Tri 3 than the previous call needed.

We can close this issue I think if everyone's tests clean up with this commit.

**Comment by ikalash** [comment]
Thanks for doing that so fast, @gahansen !  I will test it now and report back the results.

**Comment by mperego** [comment]
@gahansen yeah, thanks for the quick fix!

@ikalash I pushed a quick commit to change the test build type from Epetra to Tpetra, otherwise you might see errors in Tpetra only builds.

**Comment by ikalash** [comment]
I verified that the tests Mauro added pass now, but the CismAlbany test that uses the Ascii2D mesh struct that actually uncovered this issue is still failing on the mesh creation step.  I am attaching the relevant input files and output for this run.  @gahansen could you please have a look?  I had to add the *.txt to the files to upload them here.  Please remove it to run.

[greenland_2d.quad.msh.txt](https://github.com/SNLComputation/Albany/files/5367744/greenland_2d.quad.msh.txt)
[greenland_2d.quad.msh.txt](https://github.com/SNLComputation/Albany/files/5367741/greenland_2d.quad.msh.txt)
[create2dExo.yaml.txt](https://github.com/SNLComputation/Albany/files/5367743/create2dExo.yaml.txt)

**Comment by mperego** [comment]
@ikalash what error you see? I just tried with those file and it worked fine on my Workstation.

**Comment by gahansen** [comment]
@ikalash - I also tried these and the problem looks like it ran OK

**Comment by gahansen** [comment]
@ikalash I just saw the CISM test error come through on the "camobap" 2020-10-13 nightly. That nightly appears to have tested ALBANY_GIT_COMMIT_ID = d5dce34a4, my fix is one commit more recent than that one (69984a372). Not sure if something like that might be at play, but I thought I would note it.

**Comment by ikalash** [comment]
@gahansen : I think you maybe were looking at the nightly from 2 nights ago?  Last night's has: ```-- ALBANY_GIT_COMMIT_ID = 90509fa36 ``` (https://sems-cdash-son.sandia.gov/cdash/buildSummary.php?buildid=7386).  Let me have a closer look at what is going on there.  It's strange that the error happens on camobap but it does not seem to happen for @gahansen or @mperego with the same build of the code.

**Comment by ikalash** [comment]
I figured out the problem.  The issue happens only in parallel.  @gahansen if you run the input files from the CismAlbany test that I posted yesterday in parallel, does it run correctly, or does it die with an ``INVALID_TOPOLOGY'' error?

**Comment by gahansen** [comment]
Sorry folks. I needed to broadcast the element topology as this is only read in on rank 0. This commit should have this new logic working in both series and parallel.

**Comment by mperego** [comment]
Thanks, Glen!

**Comment by ikalash** [comment]
Looks like this has been resolved - thanks!
